language: ruby
cache: bundler
before_install: gem install bundler
bundler_args: --without yard guard benchmarks
script: "bundle exec rake ci:metrics"
rvm:
  - 2.1.8
  - 2.2.6
  - 2.3.3
  - 2.4.0
  - ruby-head
  - rbx-3.81
notifications:
  irc:
    channels:
      - "irc.freenode.org#rom-rb"
    on_success: never
    on_failure: change
  email:
    on_success: never
    on_failure: change
matrix:
  include:
    - rvm: jruby-19mode
      env: JRUBY_OPTS="$JRUBY_OPTS --debug"
    - rvm: jruby-head
      env: JRUBY_OPTS="$JRUBY_OPTS --debug"
    - rvm: 2.4.0
      env: WITH_MUTANT=true
      script: "bundle exec rake ci" # include mutant
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-3.81
    - rvm: jruby-19mode
    - rvm: jruby-head
    - env: WITH_MUTANT=true
  fast_finish: true
